export enum Perfiles {
    OPERADOR_VENTA = 'OPERADOR VENTA',
    OPERADOR_AUDITORIA = 'OPERADOR AUDITORIA',
    OPERADOR_LOGISTICA = 'OPERADOR LOGISTICA',
    OPERADOR_VALIDACION = 'OPERADOR VALIDACION',
    SUPERVISOR_CALL = 'SUPERVISOR CALL',
    SUPERVISOR_VENDEDORAS = 'SUPERVISOR VENDEDORAS',
    ADMINISTRADO_VENTAS = 'ADMINISTRADOR VENTAS',
    SUPERVISOR_LOGISTICA = 'SUPERVISOR LOGISTICA',
    ESTADISTICAS = 'ESTADISTICAS',
    VENDEDORA = 'VENDEDORA',
    CADETE = 'CADETE',
    EXTERNO = 'EXTERNO',
    PROMOTORA = 'PROMOTORA',
    TEAM_LEADER = 'TEAM LEADER'
}